plots:
#  fmnist_non_iid_sud_acc:
#    df_name: fmnist_non_iid_sud_acc
#    source:
#      tag: Server Acc1
#      lines:
#        - name: FedAvg
#          path: "~/ma-logs/FMNIST/FEDAVG"
#          match: FMNIST_NON_IID_SUD_FEDAVG_seed
#        - name: MAX-CS
#          path: "~/ma-logs/FMNIST/MAXCS"
#          match: FMNIST_NON_IID_SUD_MAXCS_seed
#        - name: UCB-CS
#          path: "~/ma-logs/FMNIST/UCBCS"
#          match: FMNIST_NON_IID_SUD_UCBCS_seed
#    plot:
#      legend: [FedAvg, MAX-CS, UCB-CS]
#      labels: {x: Round, y: Accuracy}
#      ylim: [0.5, 1]

  mnist_non_iid_sud_acc:
    df_name: mnist_non_iid_sud_acc
    source:
      tag: Server Acc1
      lines:
        - name: FedAvg
          path: "~/ma-logs/MNIST/SUD/FEDAVG"
          match: MNIST_NON_IID_SUD_FEDAVG_seed
        - name: MAX-CS
          path: "~/ma-logs/MNIST/SUD/MAXCS"
          match: MNIST_NON_IID_SUD_MAXCS_seed
        - name: UCB-CS
          path: "~/ma-logs/MNIST/SUD/UCBCS"
          match: MNIST_NON_IID_SUD_UCBCS_seed
        - name: UCB-CS (W=5)
          path: "~/ma-logs/MNIST/SUD/UCBCS_W5"
          match: MNIST_NON_IID_SUD_UCBCS_W5_seed
    plot:
      legend: [FedAvg, MAX-CS, UCB-CS, UCB-CS (W=5)]
      labels: {x: Round, y: Accuracy}
      ylim: [0, 1]
      scale: exp

  mnist_non_iid_inc_acc:
    df_name: mnist_non_iid_inc_acc
    source:
      tag: Server Acc1
      lines:
        - name: FedAvg
          path: "~/ma-logs/MNIST/INC/FEDAVG"
          match: MNIST_NON_IID_INC_FEDAVG_seed
        - name: MAX-CS
          path: "~/ma-logs/MNIST/INC/MAXCS"
          match: MNIST_NON_IID_INC_MAXCS_seed
        - name: UCB-CS
          path: "~/ma-logs/MNIST/INC/UCBCS"
          match: MNIST_NON_IID_INC_UCBCS_seed
        - name: UCB-CS (W=5)
          path: "~/ma-logs/MNIST/INC/UCBCS_W5"
          match: MNIST_NON_IID_INC_UCBCS_W5_seed
    plot:
      legend: [FedAvg, MAX-CS, UCB-CS, UCB-CS (W=5)]
      labels: {x: Round, y: Accuracy}
      ylim: [0, 1]
      scale: exp

  fmnist_non_iid_inc_acc:
    df_name: fmnist_non_iid_inc_acc
    source:
      tag: Server Acc1
      lines:
        - name: FedAvg
          path: "~/ma-logs/FMNIST/INC/FEDAVG"
          match: FMNIST_NON_IID_INC_FEDAVG_seed
        - name: MAX-CS
          path: "~/ma-logs/FMNIST/INC/MAXCS"
          match: FMNIST_NON_IID_INC_MAXCS_seed
        - name: UCB-CS
          path: "~/ma-logs/FMNIST/INC/UCBCS"
          match: FMNIST_NON_IID_INC_UCBCS_seed
        - name: UCB-CS (W=5)
          path: "~/ma-logs/FMNIST/INC/UCBCS_W5"
          match: FMNIST_NON_IID_INC_UCBCS_W5_seed
    plot:
      legend: [FedAvg, MAX-CS, UCB-CS, UCB-CS (W=5)]
      labels: {x: Round, y: Accuracy}
      ylim: [0, 1]
      scale: exp

  e_mnist_ucbcs_c:
    df_name: e_mnist_ucbcs_c
    source:
      tag: Server Acc1
      lines:
        - name: FedAvg
          path: "~/ma-logs/MNIST/SUD/FEDAVG"
          match: MNIST_NON_IID_SUD_FEDAVG_seed
        - name: c=0.5
          path: "~/ma-logs/MNIST_EXPLORE/UCBCS_C05"
          match: MNIST_NON_IID_SUD_UCBCS_C05_seed
        - name: c=1.0
          path: "~/ma-logs/MNIST_EXPLORE/UCBCS_C10"
          match: MNIST_NON_IID_SUD_UCBCS_C10_seed
        - name: c=2.0
          path: "~/ma-logs/MNIST_EXPLORE/UCBCS_C20"
          match: MNIST_NON_IID_SUD_UCBCS_C20_seed
    plot:
      legend: [FedAvg, c=0.5, c=1.0, c=2.0]
      labels: {x: Round, y: Accuracy}
      ylim: [0, 1]
      scale: exp
      hlines: 0.97
      vlines: 48

  e_mnist_ucbcs_w:
    df_name: e_mnist_ucbcs_w
    source:
      tag: Server Acc1
      lines:
        - name: FedAvg
          path: "~/ma-logs/MNIST/SUD/FEDAVG"
          match: MNIST_NON_IID_SUD_FEDAVG_seed
        - name: W=5
          path: "~/ma-logs/MNIST_EXPLORE/UCBCS_W5"
          match: MNIST_NON_IID_SUD_UCBCS_W5_seed
        - name: W=8
          path: "~/ma-logs/MNIST_EXPLORE/UCBCS_W8"
          match: MNIST_NON_IID_SUD_UCBCS_W8_seed
        - name: W=12
          path: "~/ma-logs/MNIST_EXPLORE/UCBCS_W12"
          match: MNIST_NON_IID_SUD_UCBCS_W12_seed
    plot:
      legend: [FedAvg, W=5, W=8, W=12]
      labels: {x: Round, y: Accuracy}
      ylim: [0, 1]
      scale: exp
      hlines: 0.97
      vlines: 48

  e_mnist_ucbcs_g:
    df_name: e_mnist_ucbcs_g
    source:
      tag: Server Acc1
      lines:
        - name: FedAvg
          path: "~/ma-logs/MNIST/SUD/FEDAVG"
          match: MNIST_NON_IID_SUD_FEDAVG_seed
        - name: gamma=0.80
          path: "~/ma-logs/MNIST_EXPLORE/UCBCS_G80"
          match: MNIST_NON_IID_SUD_UCBCS_G80_seed
        - name: gamma=0.90
          path: "~/ma-logs/MNIST_EXPLORE/UCBCS_G90"
          match: MNIST_NON_IID_SUD_UCBCS_G90_seed
        - name: gamma=0.95
          path: "~/ma-logs/MNIST_EXPLORE/UCBCS_G95"
          match: MNIST_NON_IID_SUD_UCBCS_G95_seed
    plot:
      legend: [FedAvg, "$\\gamma=0.80$", "$\\gamma=0.90$", "$\\gamma=0.95$"]
      labels: {x: Round, y: Accuracy}
      ylim: [0, 1]
      scale: exp
      hlines: 0.97
      vlines: 48

  chexpert_non_iid_sud_auroc:
    df_name: chexpert_non_iid_sud_auroc
    source:
      tag: Server Mlauroc
      lines:
        - name: FedAvg
          path: "~/ma-logs/CheXpert/FEDAVG"
          match: CHEXPERT_NON_IID_SUD_FEDAVG_seed
        - name: MAX-CS
          path: "~/ma-logs/CheXpert/MAXCS"
          match: CHEXPERT_NON_IID_SUD_MAXCS_seed
        - name: UCB-CS
          path: "~/ma-logs/CheXpert/UCBCS"
          match: CHEXPERT_NON_IID_SUD_UCBCS_seed
        - name: UCB-CS (W=5)
          path: "~/ma-logs/CheXpert/UCBCS_W5"
          match: CHEXPERT_NON_IID_SUD_UCBCS_W5_seed
        - name: UCB-CS (W=8)
          path: "~/ma-logs/CheXpert/UCBCS_W8"
          match: CHEXPERT_NON_IID_SUD_UCBCS_W8_seed
    plot:
      legend: [FedAvg, MAX-CS, UCB-CS, UCB-CS (W=5), UCB-CS (W=8)]
      labels: {x: Round, y: AUROC}
      ylim: [0.6, 0.8]

  chexpert_non_iid_sud_acc:
    df_name: chexpert_non_iid_sud_acc
    source:
      tag: Server Mlacc
      lines:
        - name: FedAvg
          path: "~/ma-logs/CheXpert/FEDAVG"
          match: CHEXPERT_NON_IID_SUD_FEDAVG_seed
        - name: MAX-CS
          path: "~/ma-logs/CheXpert/MAXCS"
          match: CHEXPERT_NON_IID_SUD_MAXCS_seed
        - name: UCB-CS
          path: "~/ma-logs/CheXpert/UCBCS"
          match: CHEXPERT_NON_IID_SUD_UCBCS_seed
        - name: UCB-CS (W=5)
          path: "~/ma-logs/CheXpert/UCBCS_W5"
          match: CHEXPERT_NON_IID_SUD_UCBCS_W5_seed
        - name: UCB-CS (W=8)
          path: "~/ma-logs/CheXpert/UCBCS_W8"
          match: CHEXPERT_NON_IID_SUD_UCBCS_W8_seed
    plot:
      legend: [FedAvg, MAX-CS, UCB-CS, UCB-CS (W=5), UCB-CS (W=8)]
      labels: {x: Round, y: Accuracy}
      ylim: [0.8, 0.83]

  mimic_non_iid_sud_acc:
    df_name: mimic_non_iid_sud_acc
    source:
      tag: Server Acc1
      lines:
        - name: FedAvg
          path: "~/ma-logs/MIMIC4/FEDAVG"
          match: MIMIC_NON_IID_SUD_FEDAVG_seed
        - name: MAX-CS
          path: "~/ma-logs/MIMIC4/MAXCS"
          match: MIMIC_NON_IID_SUD_MAXCS_seed
#        - name: UCB-CS (loss)
#          path: "~/ma-logs/MIMIC4/UCBCS"
#          match: MIMIC_NON_IID_SUD_UCBCS_seed
        - name: UCB-CS (W=5)
          path: "~/ma-logs/MIMIC4/UCBCS_W5"
          match: MIMIC_NON_IID_SUD_UCBCS_W5_seed
        - name: UCB-CS (W=8)
          path: "~/ma-logs/MIMIC4/UCBCS_W8"
          match: MIMIC_NON_IID_SUD_UCBCS_W8_seed
    plot:
      legend:
        - FedAvg
        - MAX-CS
#        - UCB-CS (loss)
        - UCB-CS (W=5)
        - UCB-CS (W=8)
      labels: {x: Round, y: Accuracy}
      ylim: [0.8, 0.92]

  mimic_non_iid_sud_auprc:
    df_name: mimic_non_iid_sud_auprc
    source:
      tag: Server Auprc
      lines:
        - name: FedAvg
          path: "~/ma-logs/MIMIC4/FEDAVG"
          match: MIMIC_NON_IID_SUD_FEDAVG_seed
        - name: MAX-CS
          path: "~/ma-logs/MIMIC4/MAXCS"
          match: MIMIC_NON_IID_SUD_MAXCS_seed
#        - name: UCB-CS (loss)
#          path: "~/ma-logs/MIMIC4/UCBCS"
#          match: MIMIC_NON_IID_SUD_UCBCS_seed
        - name: UCB-CS (W=5)
          path: "~/ma-logs/MIMIC4/UCBCS_W5"
          match: MIMIC_NON_IID_SUD_UCBCS_W5_seed
        - name: UCB-CS (W=8)
          path: "~/ma-logs/MIMIC4/UCBCS_W8"
          match: MIMIC_NON_IID_SUD_UCBCS_W8_seed
    plot:
      legend:
        - FedAvg
        - MAX-CS
#        - UCB-CS (loss)
        - UCB-CS (W=5)
        - UCB-CS (W=8)
      labels: {x: Round, y: AUPRC}
      ylim: [0.55, 0.7]
      xlim: [390, 440]

  mimic_non_iid_sud_auprc_init:
    df_name: mimic_non_iid_sud_auprc
    source:
      tag: Server Auprc
      lines:
        - name: FedAvg
          path: "~/ma-logs/MIMIC4/FEDAVG"
          match: MIMIC_NON_IID_SUD_FEDAVG_seed
        - name: MAX-CS
          path: "~/ma-logs/MIMIC4/MAXCS"
          match: MIMIC_NON_IID_SUD_MAXCS_seed
        #        - name: UCB-CS (loss)
        #          path: "~/ma-logs/MIMIC4/UCBCS"
        #          match: MIMIC_NON_IID_SUD_UCBCS_seed
        - name: UCB-CS (W=5)
          path: "~/ma-logs/MIMIC4/UCBCS_W5"
          match: MIMIC_NON_IID_SUD_UCBCS_W5_seed
        - name: UCB-CS (W=8)
          path: "~/ma-logs/MIMIC4/UCBCS_W8"
          match: MIMIC_NON_IID_SUD_UCBCS_W8_seed
    plot:
      legend:
        - FedAvg
        - MAX-CS
        #        - UCB-CS (loss)
        - UCB-CS (W=5)
        - UCB-CS (W=8)
      labels: { x: Round, y: AUPRC }
      ylim: [ 0.5, 0.7 ]
      xlim: [ 0, 250 ]
