python3 main.py \
    --exp_name "FedAvg_MNIST_2NN_IID_MaxCS_SuddenDrift" --seed 42 --device mps \
    --dataset MNIST \
    --split_type iid --test_size 0.2 \
    --model_name TwoNN --resize 28 --hidden_size 200 \
    --algorithm fedavg --eval_fraction 1 --eval_type both --eval_every 1 --eval_metrics acc1 \
    --K 100 --R 100 --E 1 --C 0.4 --B 10 --beta1 0 \
    --optimizer SGD --lr 0.1 --lr_decay 0.99 --lr_decay_step 25 --criterion CrossEntropyLoss \
    --use_tb \
    --active_sampling --sampling_fraction 0.25 --sampling_type max \
    --concept_drift --drift_mode sudden --drift_start 40 --drift_duration 1